language: android
android:
  components:
  - android-22
  - build-tools-22.0.1
  licenses:
  - android-sdk-license-[0-9a-f]{8}
branches:
  only:
  - master
script: ./gradlew clean assembleDebug lintDebug
deploy:
  provider: releases
  api_key:
    secure: Ze3W3H4AqGpdV6aEb+DPLwkF10tHpLRfUasaY02cKd6G4cupkXlFxmFy2rJiEsodkZtOyt2T+yaOrL6hevDSsA+ycGdl2WsK5oilTiSVsm11Xdqk9F+Ek+GupNh0gwZNd4IqXkhdm085r9yXqooKnblw8KI6wfLVZ4TcuvNw4xA=
  file: ./LuasTimes/build/outputs/apk/LuasTimes-debug.apk
  on:
    repo: baz8080/LuasTimesDroid
