sudo: false
jdk:
- oraclejdk8
language: android
android:
  components:
  - tools
  - android-26
  - build-tools-26.0.2
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - ".+"
script: "./gradlew clean assemble lint"
deploy:
  provider: releases
  api_key:
    secure: PBkRsWJIS/jZl1CQ/4FR+50Uq+zi0JX99jN4ros/gEhiMQ7uRqqQz5KbwaqdY/kvWFm+4BYXDa6FQSvdYGCvOxKcGuzClFiSYXU+OOINX8ITB4VoH5fO6U8dZPh7odIEwJKn5kmyYhPMbdh5QNTo4xUIJ/bfK7I0REHdQnU+o4E=
  file:
  - ./LuasTimes/build/outputs/apk/LuasTimes-debug.apk
  - ./LuasTimes/build/outputs/apk/LuasTimes-release.apk
  skip_cleanup: true
  on:
    repo: baz8080/LuasTimesDroid
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_338cfeec668d_key -iv $encrypted_338cfeec668d_iv
  -in enc.tgz.enc -out enc.tgz -d
- tar zxf enc.tgz
env:
  global:
  - secure: AdT+w9znWrkVLci5zzulDEwkAzeCEQtXLiOJbWGfuViJD9hZb+Iby7V2WesroskHsrqUFItGoLoItzYZMrhAIrX6d/P9ZxwTwRqVy/gdx/6bL0LQG+cQCPfvUhCznj1VR6WKeevN07y9BKUl8Piv6bdhy27q/BjNGWrUlFFYgwc=
  - secure: CvEZolyUwMOcu7EnlxlItTKhdUKiY8QUIexxugtXYgypadEBnhz3BcMWpCV+uNy9rq6dP0FOg6UH5M5gpCUj+DtR687UNVSnPh/yZWC9Pp3gAg9zYDzTbgo6908PqZNAWsO9u7t1vesRzMXQHoheBF0Dm7rXRIJqnFQ5hipZamw=