sudo: false
jdk:
- oraclejdk8
language: android
android:
  components:
  - tools
  - android-26
  - build-tools-26.0.2
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - ".+"
script: "./gradlew clean assemble lint"
before_install:
- openssl aes-256-cbc -K $encrypted_338cfeec668d_key -iv $encrypted_338cfeec668d_iv
  -in enc.tgz.enc -out enc.tgz -d
- tar zxf enc.tgz
env:
  global:
  - secure: AdT+w9znWrkVLci5zzulDEwkAzeCEQtXLiOJbWGfuViJD9hZb+Iby7V2WesroskHsrqUFItGoLoItzYZMrhAIrX6d/P9ZxwTwRqVy/gdx/6bL0LQG+cQCPfvUhCznj1VR6WKeevN07y9BKUl8Piv6bdhy27q/BjNGWrUlFFYgwc=
  - secure: CvEZolyUwMOcu7EnlxlItTKhdUKiY8QUIexxugtXYgypadEBnhz3BcMWpCV+uNy9rq6dP0FOg6UH5M5gpCUj+DtR687UNVSnPh/yZWC9Pp3gAg9zYDzTbgo6908PqZNAWsO9u7t1vesRzMXQHoheBF0Dm7rXRIJqnFQ5hipZamw=
deploy:
  provider: releases
  api_key:
    secure: pNAiPkjZe0fHYLLvC45UCrSk+XeZqpF+xVJAUIkMkEnmjsry5WVMm0nORLMsxmG8TffwVjUv/TKzTL+/M0aDU4HdkD/V4NuHlnft122Ct/ioMp0prgCok+ulhhMT8/hAtIssHJMXvNThCqf84wXm6q5wdpfdaP8IGfyHm77L+wQ=
  file: ./LuasTimes/build/outputs/apk/LuasTimes-release.apk
  skip_cleanup: true
  on:
    repo: baz8080/LuasTimesDroid
    tags: true
