language: android
android:
  components:
    - android-22
    - build-tools-22.0.1
  licenses:
    - android-sdk-license-[0-9a-f]{8}
branches:
  only:
    - master

script: ./gradlew clean assembleDebug lintDebug