language: android
android:
  components:
  - android-22
  - build-tools-22.0.1
  licenses:
  - android-sdk-license-[0-9a-f]{8}
script: ./gradlew clean assembleDebug lintDebug
deploy:
  provider: releases
  api_key:
    secure: Ze3W3H4AqGpdV6aEb+DPLwkF10tHpLRfUasaY02cKd6G4cupkXlFxmFy2rJiEsodkZtOyt2T+yaOrL6hevDSsA+ycGdl2WsK5oilTiSVsm11Xdqk9F+Ek+GupNh0gwZNd4IqXkhdm085r9yXqooKnblw8KI6wfLVZ4TcuvNw4xA=
  file: ./LuasTimes/build/outputs/apk/LuasTimes-debug.apk
  skip_cleanup: true
  on:
    repo: baz8080/LuasTimesDroid
    tags: true
    all_branches: true
before_install:
- openssl aes-256-cbc -K $encrypted_338cfeec668d_key -iv $encrypted_338cfeec668d_iv
  -in scripts/keystore.enc -out scripts/release.keystore -d
env:
  global:
  - secure: AdT+w9znWrkVLci5zzulDEwkAzeCEQtXLiOJbWGfuViJD9hZb+Iby7V2WesroskHsrqUFItGoLoItzYZMrhAIrX6d/P9ZxwTwRqVy/gdx/6bL0LQG+cQCPfvUhCznj1VR6WKeevN07y9BKUl8Piv6bdhy27q/BjNGWrUlFFYgwc=
  - secure: oBykuOc8UuEDp1EImT0PYRqXrrQNNBEo8zdtpgbqEBl0+w7W5nsaCeFeNfb8Y+lA6WhMEokjQvO5ciBgXedTks29Sc30HukGRy1dv2cyJeB+JE6Y3Khvvjef44Q8nc5EZwhGBMRj76n0Wl+6BacE24DRZuH14qOr2pMOLQ+NW84=
